---
services:
  gh-actions-for-devops-readme:
    container_name: gh-actions-for-devops-readme
    build:
      context: ./src
      dockerfile: Dockerfile
    image: dceoy/gh-actions-for-devops-readme:latest
    network_mode: none
    volumes:
      - ${PWD}:/workspace
    working_dir: /workspace/src
    entrypoint:
      - python
    command:
      - ./build_readme_md.py
