---
services:
  gh-actions-for-devops-readme:
    container_name: gh-actions-for-devops-readme
    build:
      context: ./src
      dockerfile: Dockerfile
    image: dceoy/gh-actions-for-devops-readme:latest
    network_mode: none
    volumes:
      - ${PWD}:/wd
    working_dir: /wd/src
    entrypoint:
      - /usr/local/bin/poetry
    command:
      - run
      - python
      - ./build_readme_md.py
