---
version: '3'

services:
  build-readme-md:
    container_name: build-readme-md
    build:
      context: ./src
      dockerfile: Dockerfile
    image: build-readme-md:latest
    volumes:
      - ${PWD}:/wd
    working_dir: /wd/src
    entrypoint:
      - /usr/local/bin/poetry
    command:
      - run
      - python
      - ./build_readme_md.py
