[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "build_readme_md"
version = "v0.0.1"
description = "README.md build script"
authors = []
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
Jinja2 = "^3.1.3"
PyYAML = "^6.0.1"

[tool.poetry.dev-dependencies]
autopep8 = "^2.0.4"
bandit = "^1.7.7"
flake8 = "^7.0.0"
flake8-bugbear = "^24.2.6"
flake8-isort = "^6.1.1"
pep8-naming = "^0.13.3"
mypy = "^1.8.0"
ruff = "^0.3.0"

[tool.poetry.scripts]
build-readme-md = "build_readme_md:main"
