[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "build_readme_md"
version = "v0.0.1"
description = "README.md build script"
authors = []
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
Jinja2 = "^3.1.4"
PyYAML = "^6.0.1"

[tool.poetry.dev-dependencies]
autopep8 = "^2.3.1"
bandit = "^1.7.9"
flake8 = "^7.1.0"
flake8-bugbear = "^24.4.26"
flake8-isort = "^6.1.1"
pep8-naming = "^0.14.1"
mypy = "^1.10.1"
ruff = "^0.5.3"
