---
name: Claude Code action using Amazon Bedrock
on:
  issue_comment:
    types:
      - created
  pull_request_review_comment:
    types:
      - created
  issues:
    types:
      - opened
      - assigned
  pull_request_review:
    types:
      - submitted
permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write
env:
  AWS_REGION: us-west-2
  AMAZON_BEDROCK_MODEL: us.anthropic.claude-sonnet-4-20250514-v1:0
jobs:
  claude-code-action:
    if: >
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude'))
      || (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude'))
      || (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude'))
      || (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    outputs:
      execution-file: ${{ steps.claude-code-action.outputs.execution_file }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df  # v4.2.1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run Claude PR Action
        id: claude-code-action
        uses: anthropics/claude-code-action@3486c33ebfa03d71c98e72621759471c45388443  # v0.0.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          model: ${{ env.AMAZON_BEDROCK_MODEL }}
          use_bedrock: true
          timeout_minutes: 60
          trigger_phrase: '@claude'
          assignee_trigger: '@claude'
