---
name: Docker image build and push using docker-compose
on:
  workflow_call:
    with:
      inputs:
        file:
          required: false
          type: string
          description: Path to Docker Compose file
          default: docker-compose.yml
    secrets:
      DOCKER_USER:
        required: true
        description: Docker Hub username
      DOCKER_TOKEN:
        required: true
        description: Docker Hub token
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push the image
        run: |
          docker-compose -f ${{ github.event.inputs.file }} build --pull --push
