---
name: CI to Docker Hub
on:
  workflow_call:
    secrets:
      DOCKER_USER:
        required: true
        type: string
        description: Docker Hub username
        default: ${{ github.actor }}
      DOCKER_TOKEN:
        required: true
        type: string
        description: Docker Hub token
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push an image
        run: |
          docker-compose build && docker-compose push
