---
name: Docker image save and resource deployment to AWS using Terraform
on:
  workflow_call:
    inputs:
      docker-image-name-to-target-stage-json:
        required: false
        type: string
        description: JSON object with Docker image names as keys and Docker build target stages as values
        default: null
      docker-registry:
        required: false
        type: string
        description: Image registry to login (e.g., ghcr.io, docker.io)
        default: null
      docker-registry-user:
        required: false
        type: string
        description: Image registry username
        default: ${{ github.repository_owner }}
      docker-build-context:
        required: false
        type: string
        description: Docker build's context is the set of files located in the specified PATH or URL
        default: .
      dockerfile:
        required: false
        type: string
        description: Path to a Dockerfile
        default: Dockerfile
      docker-platforms:
        required: false
        type: string
        description: List of target platforms for build
        default: linux/amd64,linux/arm64
      docker-build-args:
        required: false
        type: string
        description: List of build-time variables
        default: null
      docker-secrets:
        required: false
        type: string
        description: List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)
        default: null
      docker-secret-envs:
        required: false
        type: string
        description: List of secret env vars to expose to the build (e.g., key=envname, MY_SECRET=MY_ENV_VAR)
        default: null
      docker-secret-files:
        required: false
        type: string
        description: List of secret files to expose to the build (e.g., key=filename, MY_SECRET=./secret.txt)
        default: null
      cosign:
        required: false
        type: boolean
        description: Sign the image with cosign
        default: false
      scan-before-build:
        required: false
        type: boolean
        description: Scan Dockerfile before build
        default: true
      scan-after-build:
        required: false
        type: boolean
        description: Scan Docker image after build
        default: true
      scan-after-pull:
        required: false
        type: boolean
        description: Scan the image after pull
        default: true
      use-hadolint:
        required: false
        type: boolean
        description: Use Hadolint linter
        default: true
      hadolint-failure-threshold:
        required: false
        type: string
        description: Hadolint failure threshold
        default: error
      hadolint-recursive:
        required: false
        type: boolean
        description: Search for Dockerfile recursively from the project root
        default: true
      trivy-scanners:
        required: false
        type: string
        description: List of scanners to use
        default: vuln,secret,misconfig
      trivy-severity:
        required: false
        type: string
        description: Severity levels to fail the scan
        default: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
      trivy-ignore-unfixed:
        required: false
        type: boolean
        description: Ignore unpatched/unfixed vulnerabilities
        default: true
      trivy-filesystem-exit-code:
        required: false
        type: number
        description: Exit code for trivy filesystem
        default: 1
      trivy-image-exit-code:
        required: false
        type: number
        description: Exit code for trivy image
        default: 0
      trivy-config:
        required: false
        type: string
        description: Path to a Trivy config file
        default: null
      trivy-timeout:
        required: false
        type: string
        description: Timeout for the Trivy scan
        default: 5m0s
      docker-image-names-to-pull:
        required: false
        type: string
        description: Docker image names to pull (separated by spaces or returns)
        default: null
      docker-tag-source-to-target-json:
        required: false
        type: string
        description: JSON object with source image names as keys and target image tags as values
        default: null
      target-aws-iam-role-to-assume:
        required: false
        type: string
        description: AWS IAM role ARN to assume for resource deployment
        default: null
      target-aws-region:
        required: false
        type: string
        description: AWS region to use for resource deployment
        default: us-east-1
      target-aws-profile-env-file:
        required: false
        type: string
        description: Path to the file containing the target AWS profile environment variables
        default: null
      source-aws-iam-role-to-assume:
        required: false
        type: string
        description: AWS IAM role ARN to assume for Docker image pull
        default: null
      source-aws-region:
        required: false
        type: string
        description: AWS region to use for Docker image pull
        default: us-east-1
      source-aws-profile-env-file:
        required: false
        type: string
        description: Path to the file containing the source AWS profile environment variables
        default: null
      terraform-or-terragrunt-working-directory:
        required: false
        type: string
        description: Working directory for Terraform or Terragrunt
        default: .
      apply:
        required: false
        type: boolean
        description: Create or update infrastructure
        default: false
      terraform-version:
        required: false
        type: string
        description: Terraform version to use
        default: latest
      terragrunt-version:
        required: false
        type: string
        description: Terragrunt version to use
        default: null
      terraform-output-pattern-for-docker-image-uri:
        required: false
        type: string
        description: Terraform output variable pattern for the Docker image URI
        default: image_uri
      docker-metadata-action-images:
        required: false
        type: string
        description: Images for the Docker metadata action
        default: null
      docker-metadata-action-tags:
        required: false
        type: string
        description: Tags for the Docker metadata action
        default: |
          type=sha
          type=sha,format=long
          type=raw,value=latest
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
      docker-image-artifact-name:
        required: false
        type: string
        description: Docker image tarball artifact name to download
        default: docker-image
      docker-image-artifact-retention-days:
        required: false
        type: number
        description: Number of days to retain artifacts
        default: 1
      docker-image-artifact-overwrite:
        required: false
        type: boolean
        description: Overwrite existing artifacts
        default: true
      runs-on:
        required: false
        type: string
        description: GitHub Actions runner to use
        default: ubuntu-latest
      timeout-minutes:
        required: false
        type: number
        description: Timeout in minutes for the job
        default: 360
permissions:
  contents: read    # This is required for actions/checkout
  id-token: write   # This is required for requesting the JWT
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  build:
    if: >
      inputs.apply && inputs.docker-image-name-to-target-stage-json != null
    uses: ./.github/workflows/docker-build-with-multi-targets.yml
    with:
      image-name-to-target-stage-json: ${{ inputs.docker-image-name-to-target-stage-json }}
      registry: ${{ inputs.docker-registry }}
      registry-user: ${{ inputs.docker-registry-user }}
      context: ${{ inputs.docker-build-context }}
      file: ${{ inputs.dockerfile }}
      platforms: ${{ inputs.docker-platforms }}
      build-args: ${{ inputs.docker-build-args }}
      secrets: ${{ inputs.docker-secrets }}
      secret-envs: ${{ inputs.docker-secret-envs }}
      secret-files: ${{ inputs.docker-secret-files }}
      cosign: ${{ inputs.cosign }}
      push: false
      scan-before-build: ${{ inputs.scan-before-build }}
      scan-after-build: ${{ inputs.scan-after-build }}
      use-hadolint: ${{ inputs.use-hadolint }}
      hadolint-failure-threshold: ${{ inputs.hadolint-failure-threshold }}
      hadolint-recursive: ${{ inputs.hadolint-recursive }}
      trivy-scanners: ${{ inputs.trivy-scanners }}
      trivy-severity: ${{ inputs.trivy-severity }}
      trivy-ignore-unfixed: ${{ inputs.trivy-ignore-unfixed }}
      trivy-filesystem-exit-code: ${{ inputs.trivy-filesystem-exit-code }}
      trivy-image-exit-code: ${{ inputs.trivy-image-exit-code }}
      trivy-config: ${{ inputs.trivy-config }}
      trivy-timeout: ${{ inputs.trivy-timeout }}
      docker-metadata-action-tags: ${{ inputs.docker-metadata-action-tags }}
      image-artifact-name: ${{ inputs.docker-image-artifact-name }}
      image-artifact-retention-days: ${{ inputs.docker-image-artifact-retention-days }}
      image-artifact-overwrite: ${{ inputs.docker-image-artifact-overwrite }}
      runs-on: ${{ inputs.runs-on }}
      timeout-minutes: ${{ inputs.timeout-minutes }}
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
  pull:
    if: >
      inputs.apply && inputs.docker-image-name-to-target-stage-json == null
      && (inputs.docker-image-names-to-pull != null || inputs.docker-tag-source-to-target-json != null)
    uses: ./.github/workflows/docker-pull-from-aws.yml
    with:
      image-names: ${{ inputs.docker-image-names-to-pull }}
      tag-source-to-target-json: ${{ inputs.docker-tag-source-to-target-json }}
      aws-iam-role-to-assume: ${{ inputs.source-aws-iam-role-to-assume }}
      aws-region: ${{ inputs.source-aws-region }}
      aws-profile-env-file: ${{ inputs.source-aws-profile-env-file }}
      image-artifact-name: ${{ inputs.docker-image-artifact-name }}
      image-artifact-retention-days: ${{ inputs.docker-image-artifact-retention-days }}
      image-artifact-overwrite: ${{ inputs.docker-image-artifact-overwrite }}
      scan-after-pull: ${{ inputs.scan-after-pull }}
      trivy-scanners: ${{ inputs.trivy-scanners }}
      trivy-severity: ${{ inputs.trivy-severity }}
      trivy-ignore-unfixed: ${{ inputs.trivy-ignore-unfixed }}
      trivy-exit-code: ${{ inputs.trivy-image-exit-code }}
      trivy-config: ${{ inputs.trivy-config }}
      trivy-timeout: ${{ inputs.trivy-timeout }}
      runs-on: ${{ inputs.runs-on }}
      timeout-minutes: ${{ inputs.timeout-minutes }}
  deploy:
    if: >
      (! (failure() || cancelled()))
    needs:
      - build
      - pull
    uses: ./.github/workflows/terraform-deploy-to-aws.yml
    with:
      aws-iam-role-to-assume: ${{ inputs.target-aws-iam-role-to-assume }}
      aws-region: ${{ inputs.target-aws-region }}
      aws-profile-env-file: ${{ inputs.target-aws-profile-env-file }}
      terraform-or-terragrunt-working-directory: ${{ inputs.terraform-or-terragrunt-working-directory }}
      apply: ${{ inputs.apply }}
      terraform-version: ${{ inputs.terraform-version }}
      terragrunt-version: ${{ inputs.terragrunt-version }}
      use-docker: true
      docker-metadata-action-images: ${{ inputs.docker-metadata-action-images }}
      docker-metadata-action-tags: ${{ inputs.docker-metadata-action-tags }}
      docker-image-artifact-name: ${{ inputs.docker-image-artifact-name }}
      runs-on: ${{ inputs.runs-on }}
      timeout-minutes: ${{ inputs.timeout-minutes }}
