---
name: Docker image build and save
on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: list
        description: List of tags
      context:
        required: false
        type: string
        description: Build's context is the set of files located in the specified PATH or URL
        default: .
      file:
        required: false
        type: string
        description: Path to the Dockerfile
        default: Dockerfile
      build-args:
        required: false
        type: list
        description: List of build-time variables
        default: null
      platforms:
        required: false
        type: list
        description: List of target platforms for build
        default: linux/amd64
      artifact-name:
        required: false
        type: string
        description: Name of the artifact to upload
        default: docker-image
      retention-days:
        required: false
        type: number
        description: Number of days to retain artifacts
        default: 1
    secrets:
      DOCKER_USER:
        required: false
        description: Docker Hub username
        default: null
      DOCKER_TOKEN:
        required: false
        description: Docker Hub token
        default: null
jobs:
  build-and-save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: ${{ secrets.DOCKER_USER && secrets.DOCKER_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build the image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ inputs.tags }}
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          build-args: ${{ inputs.build-args }}
          platforms: ${{ inputs.platforms }}
          pull: true
          push: false
      - name: Save the image
        shell: bash -euo pipefail
        run: |
          docker save ${{ inputs.tags[0] }} \
            | gzip - > ${{ inputs.artifact-name }}.tar.gz
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-name }}.tar.gz
          retention-days: ${{ inputs.retention-days }}
