---
name: Docker image build and push
on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
        description: List of tags
      context:
        required: false
        type: string
        description: Build's context is the set of files located in the specified PATH or URL
        default: .
      file:
        required: false
        type: string
        description: Path to a Dockerfile
        default: Dockerfile
      build-args:
        required: false
        type: string
        description: List of build-time variables
        default: null
      platforms:
        required: false
        type: string
        description: List of target platforms for build
        default: linux/arm64
      push:
        required: false
        type: boolean
        description: Push an image to the registry
        default: true
      save-artifact:
        required: false
        type: boolean
        description: Save the image as an artifact
        default: false
      artifact-name:
        required: false
        type: string
        description: Name of the artifact to upload
        default: docker-image
      retention-days:
        required: false
        type: number
        description: Number of days to retain artifacts
        default: 1
    secrets:
      DOCKER_USER:
        required: false
        description: Docker Hub username
        default: null
      DOCKER_TOKEN:
        required: false
        description: Docker Hub token
        default: null
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DIST_DIR: /tmp/docker-image-dist-${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: ${{ secrets.DOCKER_USER && secrets.DOCKER_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push an image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ inputs.tags }}
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          build-args: ${{ inputs.build-args }}
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push }}
          pull: true
      - name: Save the image
        if: ${{ inputs.save-artifact }}
        shell: bash -euo pipefail
        env:
          TAGS: ${{ inputs.tags }}
        run: >
          mkdir -p "${DIST_DIR}"
          && docker save "${TAGS%%,*}"
          | gzip - > "${DIST_DIR}/${{ inputs.artifact-name }}.tar.gz"
      - name: Upload the artifact
        if: ${{ inputs.save-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ env.DIST_DIR }}
          retention-days: ${{ inputs.retention-days }}
