---
name: Docker image build and push
on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: list
        description: List of tags
      context:
        required: false
        type: string
        description: Build's context is the set of files located in the specified PATH or URL
        default: .
      file:
        required: false
        type: string
        description: Path to the Dockerfile
        default: Dockerfile
      build-args:
        required: false
        type: list
        description: List of build-time variables
        default: null
      platforms:
        required: false
        type: list
        description: List of target platforms for build
        default: linux/amd64
    secrets:
      DOCKER_USER:
        required: true
        description: Docker Hub username
      DOCKER_TOKEN:
        required: true
        description: Docker Hub token
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push the image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ inputs.tags }}
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          build-args: ${{ inputs.build-args }}
          platforms: ${{ inputs.platforms }}
          pull: true
          push: true
