---
name: Docker image build and push using docker-compose
on:
  workflow_call:
    inputs:
      push:
        required: false
        type: boolean
        description: Push images to the registry
        default: true
      docker-compose-options:
        required: false
        type: string
        description: Additional options to pass to docker-compose
        default: null
      docker-compose-build-options:
        required: false
        type: string
        description: Additional options to pass to docker-compose build
        default: --parallel --pull
      docker-compose-push-options:
        required: false
        type: string
        description: Additional options to pass to docker-compose push
        default: null
      registry:
        required: false
        type: string
        description: The registry to push the image to
        default: docker.io  # { docker.io, ghcr.io }
      registry-user:
        required: false
        type: string
        description: Registry username
        default: ${{ github.actor }}
      runs-on:
        required: false
        type: string
        description: GitHub Actions runner to use
        default: ubuntu-latest
      timeout-minutes:
        required: false
        type: number
        description: Timeout in minutes for the job
        default: 360
    secrets:
      DOCKER_TOKEN:
        required: false
        description: Docker token
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  build-and-push:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: inputs.registry != null
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry-user }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build images
        run: >
          docker-compose ${{ inputs.docker-compose-options }}
          build ${{ inputs.docker-compose-build-options }}
      - name: Push the images
        if: inputs.push
        run: >
          docker-compose ${{ inputs.docker-compose-options }}
          push ${{ inputs.docker-compose-push-options }}
