---
name: Docker image build and push using docker-compose
on:
  workflow_call:
    inputs:
      push:
        required: false
        type: boolean
        description: Push the image to the registry
        default: true
      docker-compose-options:
        required: false
        type: string
        description: Additional options to pass to docker-compose
        default: null
      docker-compose-build-options:
        required: false
        type: string
        description: Additional options to pass to docker-compose build
        default: --parallel  --pull
      docker-compose-push-options:
        required: false
        type: string
        description: Additional options to pass to docker-compose push
        default: null
    secrets:
      DOCKER_USER:
        required: true
        description: Docker Hub username
      DOCKER_TOKEN:
        required: true
        description: Docker Hub token
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build the image
        run: >
          docker-compose ${{ inputs.docker-compose-options }}
          build ${{ inputs.docker-compose-build-options }}
      - name: Push the image
        if: ${{ inputs.push }}
        run: >
          docker-compose ${{ inputs.docker-compose-options }}
          push ${{ inputs.docker-compose-push-options }}
