---
name: Docker image build and push
on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
        description: List of image tags
      context:
        required: false
        type: string
        description: Build's context is the set of files located in the specified PATH or URL
        default: .
      file:
        required: false
        type: string
        description: Path to a Dockerfile
        default: Dockerfile
      build-args:
        required: false
        type: string
        description: List of build-time variables
        default: null
      platforms:
        required: false
        type: string
        description: List of target platforms for build
        default: linux/arm64
      login:
        required: false
        type: boolean
        description: Login to Docker Hub
        default: true
      push:
        required: false
        type: boolean
        description: Push an image to the registry
        default: true
      save-artifact:
        required: false
        type: boolean
        description: Save the image as an artifact
        default: false
      artifact-name:
        required: false
        type: string
        description: Name of the artifact to upload
        default: docker-image
      retention-days:
        required: false
        type: number
        description: Number of days to retain artifacts
        default: 1
      lint-before-build:
        required: false
        type: boolean
        description: Lint Dockerfile before build
        default: true
      hadolint-failure-threshold:
        required: false
        type: string
        description: Failure threshold for hadolint
        default: error
      scan-after-build:
        required: false
        type: boolean
        description: Scan the image after build
        default: true
      trivy-exit-code:
        required: false
        type: number
        description: Exit code for Trivy
        default: 0
      trivy-severity:
        required: false
        type: string
        description: Severity levels to fail the scan
        default: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
      trivy-scanners:
        required: false
        type: string
        description: List of scanners to use
        default: vuln,secret
    secrets:
      DOCKER_USER:
        required: false
        description: Docker Hub username
      DOCKER_TOKEN:
        required: false
        description: Docker Hub token
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DIST_DIR: /tmp/docker-image-dist-${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: ${{ inputs.login }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Lint Dockerfile
        if: ${{ inputs.lint-before-build }}
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.file }}
          failure-threshold: ${{ inputs.hadolint-failure-threshold }}
      - name: Build and push an image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ inputs.tags }}
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          build-args: ${{ inputs.build-args }}
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push }}
          pull: true
      - name: Output the first image tag
        id: output-tag
        shell: bash -euo pipefail {0}
        env:
          TAGS: ${{ inputs.tags }}
        run: >
          echo "TAG=${TAGS%%,*}" >> $GITHUB_OUTPUT
      - name: Run Trivy vulnerability scanner
        if: ${{ inputs.scan-after-build }}
        uses: aquasecurity/trivy-action@0.17.0
        with:
          scan-type: image
          image-ref: ${{ steps.output-tag.outputs.TAG }}
          exit-code: ${{ inputs.trivy-exit-code }}
          severity: ${{ inputs.trivy-severity }}
          scanners: ${{ inputs.trivy-scanners }}
          format: sarif
          output: trivy-results.sarif
      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ inputs.scan-after-build }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif
      - name: Save the image
        if: ${{ inputs.save-artifact }}
        shell: bash -euo pipefail {0}
        run: >
          mkdir -p "${DIST_DIR}"
          && docker save ${{ steps.build-and-push.outputs.TAG }}
          | gzip - > "${DIST_DIR}/${{ inputs.artifact-name }}.tar.gz"
      - name: Upload the artifact
        if: ${{ inputs.save-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ env.DIST_DIR }}
          retention-days: ${{ inputs.retention-days }}
