---
name: Lint for YAML
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    uses: ./.github/workflows/yaml-lint.yml
    with:
      search-path: .github/
      python-version: 3.x
