---
name: Lint for YAML
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    uses: ./.github/workflows/yaml-lint.yml
    with:
      search_path: .github/
