---
name: Lint for YAML
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  python-lint-and-scan:
    uses: ./.github/workflows/python-package-lint-and-scan.yml
    with:
      package-path: .
      python-version: 3.x
      flake8-options: null
      ruff-check-options: null
      mypy-options: --install-types --non-interactive
      bandit-options: --recursive
  yaml-lint:
    uses: ./.github/workflows/yaml-lint.yml
    with:
      search-path: .github/
      python-version: 3.x
