---
name: PR-agent
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
  issue_comment:
    types:
      - created
      - edited
      - deleted
  workflow_call:
    inputs:
      model:
        required: false
        type: string
        description: Model to use for the API
        default: null
      model_turbo:
        required: false
        type: string
        description: Turbo model to use for the API
        default: null
      fallback_models:
        required: false
        type: string
        description: Fallback models to use for the API
        default: null
      auto-describe:
        required: false
        type: boolean
        description: Automatically describe the pull request
        default: true
      auto-review:
        required: false
        type: boolean
        description: Automatically review the pull request
        default: true
      auto-improve:
        required: false
        type: boolean
        description: Automatically improve the pull request
        default: true
      pr-description-extra-instructions:
        required: false
        type: string
        description: Extra instructions for the pull request description
        default: null
      pr-reviewer-extra-instructions:
        required: false
        type: string
        description: Extra instructions for the pull request reviewer
        default: null
      pr-code-suggestions-extra-instructions:
        required: false
        type: string
        description: Extra instructions for the pull request code suggestions
        default: null
      pr-update-changelog-extra-instructions:
        required: false
        type: string
        description: Extra instructions for the pull request update changelog
        default: null
    secrets:
      OPENAI_API_KEY:
        required: true
        description: key for OpenAI API or Perplexity API
      OPENAI_ORGANIZATION:
        required: false
        description: OpenAI organization
env:
  PPLX_MODEL: llama-3-sonar-large-32k-chat
  PPLX_MODEL_TURBO: llama-3-sonar-large-32k-chat
  PPLX_FALLBACK_MODELS: llama-3-70b-instruct
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  pr-agent:
    if: github.event.sender.type != 'Bot'
    runs-on: ubuntu-latest
    name: Run PR-agent using OpenAI API or Perplexity API
    steps:
      - name: Run PR-agent
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORGANIZATION }}
          CONFIG.MODEL: ${{ inputs.model || env.PPLX_MODEL }}
          CONFIG.MODEL_TURBO: ${{ inputs.model_turbo || env.PPLX_MODEL_TURBO }}
          CONFIG.FALLBACK_MODELS: ${{ inputs.fallback_models || env.PPLX_FALLBACK_MODELS }}
          GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: ${{ inputs.auto-describe || 'true' }}
          GITHUB_ACTION_CONFIG.AUTO_REVIEW: ${{ inputs.auto-review || 'true' }}
          GITHUB_ACTION_CONFIG.AUTO_IMPROVE: ${{ inputs.auto-improve || 'true' }}
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: ${{ inputs.pr-description-extra-instructions || '' }}
          PR_REVIEWER.EXTRA_INSTRUCTIONS: ${{ inputs.pr-reviewer-extra-instructions || '' }}
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: ${{ inputs.pr-code-suggestions-extra-instructions || '' }}
          PR_UPDATE_CHANGELOG.EXTRA_INSTRUCTIONS: ${{ inputs.pr-update-changelog-extra-instructions || '' }}
