---
name: Lint for R
on:
  workflow_call:
    inputs:
      project-path:
        required: false
        type: string
        description: Path to an R project
        default: .
      r-version:
        required: false
        type: string
        description: R version to use
        default: release
      runs-on:
        required: false
        type: string
        description: The type of machine to run the job on
        default: ubuntu-latest
      r-libs-user:
        required: false
        type: string
        description: R library path
        default: /usr/local/lib/R/site-library
      lint-package:
        required: false
        type: boolean
        description: Run package lint
        default: false
jobs:
  lint:
    runs-on: ${{ inputs.runs-on }}
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
      R_LIBS_USER: ${{ inputs.r-libs-user }}
      LINTR_ERROR_ON_LINT: true
    steps:
      - uses: actions/checkout@v4
      - name: Set $R_LIBS_USER
        if: ${{ inputs.r-libs-user != null }}
        run: |
          echo "R_LIBS_USER=${{ inputs.r-libs-user }}" >> "${GITHUB_ENV}"
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ inputs.r-version }}
          use-public-rspm: true
      - name: Install lintr
        if: ${{ ! inputs.lint-package }}
        shell: Rscript {0}
        run: |
          install.packages(pkgs = 'lintr', dependencies = TRUE, clean = TRUE)
      - name: Install lintr and packages declared in DESCRIPTION
        if: ${{ inputs.lint-package }}
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr, local::.
          needs: lint
      - name: Execute lintr::lint_dir()
        if: ${{ ! inputs.lint-package }}
        shell: Rscript {0}
        run: |
          lintr::lint_dir(path = "${{ inputs.project-path }}")
      - name: Execute lintr::lint_package()
        if: ${{ inputs.lint-package }}
        shell: Rscript {0}
        run: |
          lintr::lint_package(path = "${{ inputs.project-path }}")
