---
name: Formatter for R
on:
  workflow_call:
    inputs:
      package-path:
        required: false
        type: string
        description: Path to an R package or project
        default: .
      r-version:
        required: false
        type: string
        description: R version to use
        default: release
      runs-on:
        required: false
        type: string
        description: Type of machine to run the job on
        default: ubuntu-latest
      r-libs-user:
        required: false
        type: string
        description: R library path
        default: /usr/local/lib/R/site-library
      format-package:
        required: false
        type: boolean
        description: Run package formatting
        default: true
      lint-before-pr:
        required: false
        type: boolean
        description: Run lint before creating a pull request
        default: true
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  lint:
    runs-on: ${{ inputs.runs-on }}
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
      R_LIBS_USER: ${{ inputs.r-libs-user }}
      LINTR_ERROR_ON_LINT: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ inputs.r-version }}
          use-public-rspm: true
      - name: Install lintr, styler, and packages declared in DESCRIPTION
        if: inputs.format-package
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr, any::styler, local::.
      - name: Install lintr and styler
        if: (! inputs.format-package)
        shell: Rscript {0}
        run: |
          install.packages(pkgs = c('lintr', 'styler'), dependencies = TRUE, clean = TRUE)
      - name: Format the codes using styler::style_pkg()
        if: inputs.format-package
        shell: Rscript {0}
        run: |
          styler::style_pkg(path = "${{ inputs.package-path }}")
      - name: Format the codes using styler::style_dir()
        if: (! inputs.format-package)
        shell: Rscript {0}
        run: |
          styler::style_dir(path = "${{ inputs.package-path }}")
      - name: Lint the codes using lintr::lint_package()
        if: inputs.lint-before-pr && inputs.format-package
        shell: Rscript {0}
        run: |
          lintr::lint_package(path = "${{ inputs.package-path }}")
      - name: Lint the codes using lintr::lint_dir()
        if: (! (inputs.lint-before-pr && inputs.format-package))
        shell: Rscript {0}
        run: |
          lintr::lint_dir(path = "${{ inputs.package-path }}")
      - name: Create a commit message
        id: commit-message
        run: |
          echo 'COMMIT_MESSAGE=Reformat R codes using styler' >> "${GITHUB_OUTPUT}"
      - name: Detect changed files and create a pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: ${{ steps.commit-message.outputs.COMMIT_MESSAGE }}
          base: ${{ github.ref }}
          branch: feature/r-package-format-${{ github.run_id }}
          title: ${{ steps.commit-message.outputs.COMMIT_MESSAGE }}
          body: |
            This PR contains the following updates:

            - ${{ steps.commit-message.outputs.COMMIT_MESSAGE }}

            This PR has been generated by
            [${{ github.workflow_ref }}](https://github.com/${{ github.repository }}/).
          delete-branch: true
          draft: false
