---
name: Formatting for R
on:
  workflow_call:
    inputs:
      package-path:
        required: false
        type: string
        description: Path to an R package or project
        default: .
      r-version:
        required: false
        type: string
        description: R version to use
        default: release
      runs-on:
        required: false
        type: string
        description: Type of machine to run the job on
        default: ubuntu-latest
      r-libs-user:
        required: false
        type: string
        description: R library path
        default: /usr/local/lib/R/site-library
      format-package:
        required: false
        type: boolean
        description: Run package formatting
        default: true
      lint-before-pr:
        required: false
        type: boolean
        description: Run lint before creating a pull request
        default: true
    secrets:
      GH_TOKEN:
        required: false
        description: GitHub token
permissions:
  contents: write
  pull-requests: write
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  format-and-pr:
    runs-on: ${{ inputs.runs-on }}
    env:
      R_LIBS_USER: ${{ inputs.r-libs-user }}
      LINTR_ERROR_ON_LINT: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Set up R
        uses: r-lib/actions/setup-r@bd49c52ffe281809afa6f0fecbf37483c5dd0b93  # v2.11.3
        with:
          r-version: ${{ inputs.r-version }}
          use-public-rspm: true
      - name: Install lintr, styler, and packages declared in DESCRIPTION
        if: inputs.format-package
        uses: r-lib/actions/setup-r-dependencies@bd49c52ffe281809afa6f0fecbf37483c5dd0b93  # v2.11.3
        with:
          extra-packages: any::lintr, any::styler, local::.
      - name: Install lintr and styler
        if: (! inputs.format-package)
        shell: Rscript {0}
        run: |
          install.packages(pkgs = c('lintr', 'styler'), dependencies = TRUE, clean = TRUE)
      - name: Format the code using styler::style_pkg()
        if: inputs.format-package
        shell: Rscript {0}
        env:
          PACKAGE_PATH: ${{ inputs.package-path }}
        run: |
          styler::style_pkg(path = Sys.getenv('PACKAGE_PATH'))
      - name: Format the code using styler::style_dir()
        if: (! inputs.format-package)
        shell: Rscript {0}
        env:
          PACKAGE_PATH: ${{ inputs.package-path }}
        run: |
          styler::style_dir(path = Sys.getenv('PACKAGE_PATH'))
      - name: Lint the code using lintr::lint_package()
        if: inputs.lint-before-pr && inputs.format-package
        shell: Rscript {0}
        env:
          PACKAGE_PATH: ${{ inputs.package-path }}
        run: |
          lintr::lint_package(path = Sys.getenv('PACKAGE_PATH'))
      - name: Lint the code using lintr::lint_dir()
        if: (! (inputs.lint-before-pr && inputs.format-package))
        shell: Rscript {0}
        env:
          PACKAGE_PATH: ${{ inputs.package-path }}
        run: |
          lintr::lint_dir(path = Sys.getenv('PACKAGE_PATH'))
      - name: Create output parameters
        id: parameters
        env:
          PR_BASE: ${{ github.head_ref || github.ref_name }}
        run: |
          {
            echo 'commit_message=Reformat R code using styler'
            echo "pr_base=${PR_BASE}"
            echo "pr_branch=automatedpr/${PR_BASE}"
          } >> "${GITHUB_OUTPUT}"
      - name: Detect changed files and create a pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e  # v7.0.8
        with:
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          commit-message: ${{ steps.parameters.outputs.commit_message }}
          title: ${{ steps.parameters.outputs.commit_message }}
          branch: ${{ steps.parameters.outputs.pr_branch }}
          base: ${{ steps.parameters.outputs.pr_base }}
          labels: automated pr
          body: |
            This PR contains the following updates:

            - ${{ steps.parameters.outputs.commit_message }}

            This PR has been generated by
            [${{ github.workflow_ref }}](https://github.com/${{ github.repository }}/).
          delete-branch: true
          draft: false
