---
name: Lint for R scripts
on:
  workflow_call:
    inputs:
      project-path:
        required: false
        type: string
        description: Path to search for files
        default: .
      exclude-path:
        required: false
        type: string
        description: Path to exclude from linting
        default: null
      r-version:
        required: false
        type: string
        description: R version to use
        default: release
      runs-on:
        required: false
        type: string
        description: The type of machine to run the job on
        default: ubuntu-latest
      r-libs-user:
        required: false
        type: string
        description: R library path
        default: null
jobs:
  lint:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Set $R_LIBS_USER
        if: ${{ inputs.r-libs-user != null }}
        run: |
          echo "R_LIBS_USER=${{ inputs.r-libs-user }}" >> "${GITHUB_ENV}"
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ inputs.r-version }}
          use-public-rspm: true
      - name: Install lintr
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        shell: Rscript {0}
        run: |
          install.packages(pkgs = 'lintr', dependencies = TRUE, clean = TRUE)
      - name: Install lintr
        shell: Rscript {0}
        run: |
          library('lintr')
          lint_dir(path = "${{ inputs.project-path }}",
                   exclusions = list.files(path = "${{ inputs.exclude-path }}",
                                           full.names = TRUE,
                                           recursive = TRUE))
