---
name: Slack messaging with attachments
on:
  workflow_dispatch:
    inputs:
      attachments-json-b64:
        required: true
        type: string
        description: Base64-encoded JSON string containing attachments to send to Slack
      slack-channel-id:
        required: true
        type: string
        description: Slack channel ID
      slack-method:
        required: false
        type: string
        description: Slack API method
        default: chat.postMessage
  workflow_call:
    inputs:
      attachments-json-b64:
        required: true
        type: string
        description: Base64-encoded JSON string containing attachments to send to Slack
      slack-channel-id:
        required: true
        type: string
        description: Slack channel ID
      slack-method:
        required: false
        type: string
        description: Slack API method
        default: chat.postMessage
    secrets:
      SLACK_API_TOKEN:
        required: true
        description: Slack API token
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  slack-post:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Base64-encoded attachments JSON
        id: decode-attachments
        env:
          ATTACHMENTS_JSON_B64: ${{ inputs.attachments-json-b64 }}
        run: >
          echo "attachments=$(base64 --decode <<< "${ATTACHMENTS_JSON_B64}" | jq -c .)"
          | tee -a "${GITHUB_OUTPUT}"
      - name: Send message to Slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a  # v2.1.1
        with:
          method: ${{ inputs.slack-method }}
          token: ${{ secrets.SLACK_API_TOKEN }}
          payload: |
            channel: ${{ inputs.slack-channel-id }}
            attachments: ${{ fromJson(steps.decode-attachments.outputs.attachments) }}  # https://api.slack.com/reference/messaging/attachments
