---
name: Terraform lock files upgrader for Terragrunt
on:
  workflow_call:
    inputs:
      terragrunt-working-directories:
        required: false
        type: string
        description: Working directories for Terragrunt (separated by spaces or returns)
        default: .
      terraform-version:
        required: false
        type: string
        description: Terraform version to use
        default: latest
      terragrunt-version:
        required: false
        type: string
        description: Terragrunt version to use
        default: latest
      runs-on:
        required: false
        type: string
        description: GitHub Actions runner to use
        default: ubuntu-latest
permissions:
  contents: write
  pull-requests: write
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  terragrunt-upgrade:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}
      - name: Install Terragrunt
        env:
          TERRAGRUNT_VERSION: ${{ inputs.terragrunt-version }}
        run: |
          arch_type="$(uname -s | tr '[:upper:]' '[:lower:]')_$([[ "$(uname -m)" == 'x86_64' ]] && echo 'amd64' || echo 'arm64')"
          if [[ "${TERRAGRUNT_VERSION}" == 'latest' ]]; then
            curl -sSL https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest \
              | jq -r ".assets[] | select(.name | endswith(\"${arch_type}\")) | .browser_download_url" \
              | xargs -t curl -sSL -o /usr/local/bin/terragrunt
          else
            curl -sSL -o /usr/local/bin/terragrunt \
              "https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_${arch_type}"
          fi
          chmod +x /usr/local/bin/terragrunt
      - name: Upgrade Terraform lock files
        run: |
          echo '${{ inputs.terragrunt-working-directories }}' \
            | tr ' ' '\n' \
            | xargs -I{} -t terragrunt run-all init \
              --terragrunt-working-directory='{}' -upgrade -reconfigure
      - name: Commit and push the changes
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          message: Upgrade Terraform lock files
          push: true
