---
name: Upgrade of Terraform lock files and pull request merge
on:
  workflow_call:
    inputs:
      terraform-working-directories:
        required: false
        type: string
        description: Terraform working directories (separated by spaces or returns)
        default: .
      terraform-working-directory-to-version-tf-json:
        required: false
        type: string
        description: JSON object with Terraform working directories as keys and Terraform version files as values
        default: null
      terragrunt-working-directories:
        required: false
        type: string
        description: Terragrunt working directories (separated by spaces or returns)
        default: null
      terraform-version:
        required: false
        type: string
        description: Terraform version to use
        default: latest
      terragrunt-version:
        required: false
        type: string
        description: Terragrunt version to use
        default: latest
      merged-pr-branch-prefix:
        required: false
        type: string
        description: Prefix of the branches to merge (e.g., dependabot/terraform/)
        default: null
      search-path-for-lint-and-scan:
        required: false
        type: string
        description: Path to search for files to lint and scan
        default: .
      trivy-scanners:
        required: false
        type: string
        description: List of scanners to use
        default: vuln,secret,misconfig
      trivy-severity:
        required: false
        type: string
        description: Severity levels to fail the scan
        default: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
      trivy-ignore-unfixed:
        required: false
        type: boolean
        description: Ignore unpatched/unfixed vulnerabilities
        default: true
      trivy-exit-code:
        required: false
        type: number
        description: Exit code for pre-build scan
        default: 1
      trivy-config:
        required: false
        type: string
        description: Path to a Trivy config file
        default: null
      trivy-timeout:
        required: false
        type: string
        description: Timeout for the Trivy scan
        default: 5m0s
      merge-pr:
        required: false
        type: boolean
        description: Whether to merge the pull request
        default: true
      runs-on:
        required: false
        type: string
        description: GitHub Actions runner to use
        default: ubuntu-latest
    secrets:
      GH_TOKEN:
        required: false
        description: GitHub token
permissions:
  contents: write
  pull-requests: write
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  branch-merge:
    if: >
      inputs.merged-pr-branch-prefix != null && github.event_name == 'pull_request'
    uses: ./.github/workflows/github-pr-branch-aggregation.yml
    with:
      branch-prefix: ${{ inputs.merged-pr-branch-prefix }}
      delete-merged-branch: false
  terraform-lock-files-upgrade:
    if: >
      (! (failure() || cancelled()))
    needs:
      - branch-merge
    uses: ./.github/workflows/terraform-lock-files-upgrade.yml
    with:
      terraform-working-directories: ${{ inputs.terraform-working-directories }}
      terraform-working-directory-to-version-tf-json: ${{ inputs.terraform-working-directory-to-version-tf-json }}
      terragrunt-working-directories: ${{ inputs.terragrunt-working-directories }}
      terraform-version: ${{ inputs.terraform-version }}
      terragrunt-version: ${{ inputs.terragrunt-version }}
      create-pr: false
      runs-on: ${{ inputs.runs-on }}
  terraform-lint-and-scan:
    needs:
      - terraform-lock-files-upgrade
    uses: ./.github/workflows/terraform-lint-and-scan.yml
    with:
      search-path: ${{ inputs.search-path-for-lint-and-scan }}
      terraform-version: ${{ inputs.terraform-version }}
      terragrunt-version: ${{ inputs.terragrunt-version }}
      trivy-scanners: ${{ inputs.trivy-scanners }}
      trivy-severity: ${{ inputs.trivy-severity }}
      trivy-ignore-unfixed: ${{ inputs.trivy-ignore-unfixed }}
      trivy-exit-code: ${{ inputs.trivy-exit-code }}
      trivy-config: ${{ inputs.trivy-config }}
      trivy-timeout: ${{ inputs.trivy-timeout }}
      terraform-validate: false
      runs-on: ${{ inputs.runs-on }}
  pr-merge:
    if: >
      inputs.merge-pr && github.event_name == 'pull_request'
    needs:
      - terraform-lint-and-scan
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
    steps:
      - name: Approve the pull request
        run: >
          gh pr review --approve "${PR_URL}"
      - name: Merge the pull request
        run: >
          gh pr merge --merge --delete-branch "${PR_URL}"
