---
name: Docker image pull and resource deployment to AWS using Terraform
on:
  workflow_call:
    inputs:
      docker-image-names:
        required: true
        type: string
        description: Docker image names to pull (separated by spaces or returns)
      new-docker-image-tags-json:
        required: false
        type: string
        description: JSON object containing new tags to apply to Docker images
        default: null
      target-aws-iam-role-to-assume:
        required: false
        type: string
        description: Target AWS IAM role ARN to assume
        default: null
      target-aws-region:
        required: false
        type: string
        description: Target AWS region to use
        default: us-east-1
      target-aws-profile-env-file:
        required: false
        type: string
        description: Path to the file containing the target AWS profile environment variables
        default: null
      source-aws-iam-role-to-assume:
        required: false
        type: string
        description: Source AWS IAM role ARN to assume
        default: null
      source-aws-region:
        required: false
        type: string
        description: Source AWS region to use
        default: us-east-1
      source-aws-profile-env-file:
        required: false
        type: string
        description: Path to the file containing the source AWS profile environment variables
        default: null
      command-working-directory:
        required: false
        type: string
        description: Working directory for Terraform or Terragrunt
        default: .
      apply:
        required: false
        type: boolean
        description: Create or update infrastructure
        default: false
      terraform-options:
        required: false
        type: string
        description: Additional options to pass to terraform
        default: null
      terraform-init-options:
        required: false
        type: string
        description: Additional options to pass to terraform init
        default: null
      terraform-validate-options:
        required: false
        type: string
        description: Additional options to pass to terraform validate
        default: null
      terraform-plan-options:
        required: false
        type: string
        description: Additional options to pass to terraform plan
        default: null
      terraform-apply-options:
        required: false
        type: string
        description: Additional options to pass to terraform apply
        default: null   # -auto-approve
      terragrunt-options:
        required: false
        type: string
        description: Additional options to pass to terragrunt
        default: null   # --terragrunt-non-interactive
      terraform-version:
        required: false
        type: string
        description: Terraform version to use
        default: latest
      terragrunt-version:
        required: false
        type: string
        description: Terragrunt version to use
        default: null
      terraform-output-pattern-for-docker-image-uri:
        required: false
        type: string
        description: Terraform output variable pattern for the Docker image URI
        default: image_uri
      docker-metadata-action-images:
        required: false
        type: string
        description: Images for the Docker metadata action
        default: null
      docker-metadata-action-tags:
        required: false
        type: string
        description: Tags for the Docker metadata action
        default: |
          type=sha
          type=sha,format=long
          type=raw,value=latest
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
      docker-image-artifact-name:
        required: false
        type: string
        description: Docker image tarball artifact name to download
        default: docker-image
      docker-image-artifact-retention-days:
        required: false
        type: number
        description: Number of days to retain artifacts
        default: 1
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  pull:
    uses: ./.github/workflows/docker-pull-from-aws.yml
    with:
      image-names: ${{ inputs.docker-image-names }}
      new-image-tags-json: ${{ inputs.new-docker-image-tags-json }}
      aws-iam-role-to-assume: ${{ inputs.source-aws-iam-role-to-assume }}
      aws-region: ${{ inputs.source-aws-region }}
      aws-profile-env-file: ${{ inputs.source-aws-profile-env-file }}
      image-artifact-name: ${{ inputs.docker-image-artifact-name }}
      image-artifact-retention-days: ${{ inputs.docker-image-artifact-retention-days }}
  deploy:
    needs:
      - pull
    uses: ./.github/workflows/terraform-deploy-to-aws.yml
    with:
      aws-iam-role-to-assume: ${{ inputs.target-aws-iam-role-to-assume }}
      aws-region: ${{ inputs.target-aws-region }}
      aws-profile-env-file: ${{ inputs.target-aws-profile-env-file }}
      command-working-directory: ${{ inputs.command-working-directory }}
      apply: ${{ inputs.apply }}
      terraform-options: ${{ inputs.terraform-apply-options }}
      terraform-init-options: ${{ inputs.terraform-init-options }}
      terraform-validate-options: ${{ inputs.terraform-validate-options }}
      terraform-plan-options: ${{ inputs.terraform-plan-options }}
      terraform-apply-options: ${{ inputs.terraform-apply-options }}
      terragrunt-options: ${{ inputs.terragrunt-options }}
      terraform-version: ${{ inputs.terraform-version }}
      terragrunt-version: ${{ inputs.terragrunt-version }}
      use-docker: true
      docker-metadata-action-images: ${{ inputs.docker-metadata-action-images }}
      docker-metadata-action-tags: ${{ inputs.docker-metadata-action-tags }}
      docker-image-artifact-name: ${{ inputs.docker-image-artifact-name }}
