---
name: Upgrade of Terraform lock files and pull request merge
on:
  workflow_call:
    inputs:
      terraform-working-directories:
        required: false
        type: string
        description: Terraform working directories (separated by spaces or returns)
        default: .
      terraform-working-directory-to-version-tf-json:
        required: false
        type: string
        description: JSON object with Terraform working directories as keys and Terraform version files as values
        default: null
      terragrunt-working-directories:
        required: false
        type: string
        description: Terragrunt working directories (separated by spaces or returns)
        default: null
      terraform-version:
        required: false
        type: string
        description: Terraform version to use
        default: latest
      search-path-for-lint-and-scan:
        required: false
        type: string
        description: Path to search for files to lint and scan
        default: .
      terragrunt-version:
        required: false
        type: string
        description: Terragrunt version to use
        default: null
      trivy-severity:
        required: false
        type: string
        description: Severity levels to fail the scan
        default: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
      trivy-ignore-unfixed:
        required: false
        type: boolean
        description: Ignore unpatched/unfixed vulnerabilities
        default: true
      trivy-exit-code:
        required: false
        type: number
        description: Exit code for pre-build scan
        default: 1
      trivy-config:
        required: false
        type: string
        description: Path to a Trivy config file
        default: null
      merge-pr:
        required: false
        type: boolean
        description: Whether to merge the pull request
        default: true
      runs-on:
        required: false
        type: string
        description: GitHub Actions runner to use
        default: ubuntu-latest
permissions:
  contents: write
  pull-requests: write
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  terraform-lock-files-upgrade:
    uses: ./.github/workflows/terraform-lock-files-upgrade.yml
    with:
      terraform-working-directories: ${{ inputs.terraform-working-directories }}
      terraform-working-directory-to-version-tf-json: ${{ inputs.terraform-working-directory-to-version-tf-json }}
      terragrunt-working-directories: ${{ inputs.terragrunt-working-directories }}
      terraform-version: ${{ inputs.terraform-version }}
      create-pr: false
      runs-on: ${{ inputs.runs-on }}
  terraform-lint-and-scan:
    needs:
      - terraform-lock-files-upgrade
    uses: ./.github/workflows/terraform-lint-and-scan.yml
    with:
      search-path: ${{ inputs.search-path-for-lint-and-scan }}
      terraform-version: ${{ inputs.terraform-version }}
      terragrunt-version: ${{ inputs.terragrunt-version }}
      trivy-severity: ${{ inputs.trivy-severity }}
      trivy-ignore-unfixed: ${{ inputs.trivy-ignore-unfixed }}
      trivy-exit-code: ${{ inputs.trivy-exit-code }}
      trivy-config: ${{ inputs.trivy-config }}
      terraform-validate: false
      runs-on: ${{ inputs.runs-on }}
  merge-pull-request:
    if: >
      inputs.merge-pr && github.event_name == 'pull_request'
    needs:
      - terraform-lint-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Merge the pull request
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review --approve "${PR_URL}"
          gh pr merge --auto --merge --delete-branch "${PR_URL}"
