---
name: Lint for YAML
on:
  workflow_call:
    inputs:
      search-path:
        required: false
        type: string
        description: Path to search for files
        default: .
      python-version:
        required: false
        type: string
        description: Python version to use
        default: 3.x
      enable-cache:
        required: false
        type: boolean
        description: Cache pinned yamllint downloads
        default: true
      cache-salt:
        required: false
        type: string
        description: Optional value used to bust the yamllint cache
        default: null
      yamllint-config-data:
        required: false
        type: string
        description: Configuration data for yamllint
        default: '{"extends": "relaxed", "rules": {"line-length": "disable"}}'
      runs-on:
        required: false
        type: string
        description: Runner to use
        default: ubuntu-slim
permissions:
  contents: read
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  lint:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Disable pip cache
        if: '! inputs.enable-cache'
        run: echo 'PIP_NO_CACHE_DIR=true' >> "${GITHUB_ENV}"
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: ${{ inputs.python-version }}
      - name: Cache yamllint
        if: inputs.enable-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          path: ~/.cache/pip
          key: yamllint-${{ runner.os }}-${{ inputs.python-version }}-1.37.1-${{ inputs.cache-salt }}
      - name: Install yamllint
        run: pip install 'yamllint==1.37.1'
      - name: Execute yamllint
        env:
          YAMLLINT_CONFIG_DATA: ${{ inputs.yamllint-config-data }}
        working-directory: ${{ inputs.search-path }}
        run: >
          git ls-files -z -- '*.yml' '*.yaml'
          | xargs -0 -t yamllint --config-data="${YAMLLINT_CONFIG_DATA}"
